--- ### 代码生成器配置
generator:
  # 排除数据表
  excludeTables:
    - DATABASECHANGELOG
    - DATABASECHANGELOGLOCK
    - gen_config
    - gen_field_config
  ## 类型映射
  typeMappings:
    MYSQL:
      Integer:
        - int
        - tinyint
        - smallint
        - mediumint
        - integer
      String:
        - varchar
        - char
        - text
        - mediumtext
        - longtext
        - tinytext
        - json
      LocalDate:
        - date
      LocalDateTime:
        - datetime
        - timestamp
      Long:
        - bigint
      Float:
        - float
      Double:
        - double
      BigDecimal:
        - decimal
      Boolean:
        - bit
  ## 模板配置
  templateConfigs:
    DO:
      # 模板路径
      templatePath: backend/Entity.ftl
      # 包名称
      packageName: model.entity
      # 排除字段
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Query:
      templatePath: backend/Query.ftl
      packageName: model.query
    Req:
      templatePath: backend/Req.ftl
      packageName: model.req
    Resp:
      templatePath: backend/Resp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
    DetailResp:
      templatePath: backend/DetailResp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Mapper:
      templatePath: backend/Mapper.ftl
      packageName: mapper
    Service:
      templatePath: backend/Service.ftl
      packageName: service
    ServiceImpl:
      templatePath: backend/ServiceImpl.ftl
      packageName: service.impl
    Controller:
      templatePath: backend/Controller.ftl
      packageName: controller
    api:
      templatePath: frontend/api.ftl
      packageName: src/apis
      extension: .ts
      backend: false
    index:
      templatePath: frontend/index.ftl
      packageName: src/views
      extension: .vue
      backend: false
    AddModal:
      templatePath: frontend/AddModal.ftl
      packageName: src/views
      extension: .vue
      backend: false
    DetailDrawer:
      templatePath: frontend/DetailDrawer.ftl
      packageName: src/views
      extension: .vue
      backend: false